[build]
builder = "NIXPACKS"

[build.nixpacks]
pkgs = ["python38"]

[deploy]
startCommand = "cd backend && python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10